### ISSUE TITLE
use keybinding other than ... ctrl + k

### ISSUE THREAD

**Issue by withrvr** [stefanbuck/jumpcat#21]
### Is your feature request related to a problem? Please describe.

as you saw also
![image](https://user-images.githubusercontent.com/69628500/147601573-75630249-b56a-4bbc-b19a-892000e568d9.png)

GitHub introduced their command palette
they are using ctrl + k

### Describe the solution you'd like

- So please add an option to change the shortcut binding
- or use another shortcut 

### Additional context

- so that we can use both
- jumpcat and default command palette also

**Comment by stefanbuck** [comment]
Hi, thanks for pointing this out. Since most of the functionality is covered by the official command palette, development of Jumpcat is on hold for now. That said, I'll work on a new version to add some of the features I miss the most. However you can change the keybinding already, just type: `>configure keyboard shortcut`.

**Comment by stefanbuck** [comment]
From v0.18 onwards the hotkey is CMD+j
